version: "3.1"

services:
  watchdog-postgresql:
    container_name: watchdog-postgresql
    image: postgres:12.2
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: "watchdog"
      POSTGRES_PASSWORD: "watchdog"
      POSTGRES_DB: "watchdog"
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - "watchdog"

  watchdog-clickhouse:
    container_name: watchdog-clickhouse
    image: altinity/clickhouse-server:21.6.1.6734-testing-arm
    restart: always
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./data/clickhouse:/var/lib/clickhouse/
    networks:
      - "watchdog"

  watchdog-redis:
    container_name: watchdog-redis
    image: redis:6
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./data/redis:/opt/redis/data
    networks:
      - "watchdog"

networks:
  watchdog:
    external: true
