version: "3.1"

services:
  watchdog-postgresql:
    container_name: watchdog-postgresql
    image: postgres:12.2
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: "watchdog"
      POSTGRES_PASSWORD: "watchdog"
      POSTGRES_DB: "watchdog"
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - "watchdog"

  watchdog-clickhouse:
    container_name: watchdog-clickhouse
    image: altinity/clickhouse-server:21.6.1.6734-testing-arm
    restart: always
    expose:
      - 8123
      - 9000
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./data/clickhouse:/var/lib/clickhouse/
    networks:
      - "watchdog"

  watchdog-redis:
    container_name: watchdog-redis
    image: redis:6
    restart: always
    expose:
      - 6379
    volumes:
      - ./data/redis:/opt/redis/data
    networks:
      - "watchdog"

  watchdog-api:
    container_name: watchdog-api
    build: ../../src/api
    restart: always
    environment:
      POSTGRES_USERNAME: "watchdog"
      POSTGRES_PASSWORD: "watchdog"
      POSTGRES_DATABASE: "watchdog"
      POSTGRES_HOST: "watchdog-postgresql"
      POSTGRES_PORT: "5432"
      NODE_ENV: "develop"
      CLICKHOUSE_HOST: "http://watchdog-clickhouse"
      CLICKHOUSE_PORT: "8123"
    depends_on:
      - watchdog-clickhouse
      - watchdog-postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.watchdog-api.loadbalancer.server.port=3000"
      - "traefik.http.routers.watchdog-api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.watchdog-api.entrypoints=web"
    networks:
      - "watchdog"

  watchdog-client:
    platform: linux/arm64
    container_name: watchdog-client
    build: 
      context: ../../src/dashboard
      args:
        API_URL: "http://localhost:8000/api/"
    restart: always
    init: true
    depends_on:
      - watchdog-api
    environment:
      API_URL: "http://localhost:8000/api/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.watchdog-client.loadbalancer.server.port=80"
      - "traefik.http.routers.watchdog-client.rule=Host(`localhost`)"
      - "traefik.http.routers.watchdog-client.entrypoints=web"
    networks:
      - "watchdog"

  watchdog-traefik:
    image: traefik:latest
    command:
          # - "--api.insecure=true" 
          - "--providers.docker"
          - "--entrypoints.web.address=:8000"
    ports:
      - "8000:8000"
      # - "8080:8080"
    volumes:
      - ./data/traefik:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - "watchdog"

networks:
  watchdog:
    external: true
